cf_backend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('account/', include('codefury_backend.urls', namespace='account')),
    path('admin/', admin.site.urls),
]

codefury_backend/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView
app_name = "codefury_backend"

urlpatterns = [
    path('employee_register/',views.employee_register, name="employee_register"),
    path('company_register/',views.company_register, name="company_register"),
    path('job_search/',views.job_search, name="job_search"),
    path('jobs_list/',views.jobs_list, name="jobs_list"),
    path('candidate_search/',views.candidate_search, name="candidate_search"),
    path('candidates_list/',views.candidates_list, name="candidates_list"),
    path('login_redirect/',views.login_redirect, name="login_redirect"),
    path('home/',views.home, name="home"),
    path('login/',LoginView.as_view(template_name='codefury_backend/login.html'),name='login'),
    path('logout/',LogoutView.as_view(template_name='codefury_backend/logout.html'),name='logout')
]

codefury_backend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Employee(models.Model):
    WORK_CHOICES=[
    ('F','Full Time'),
    ('P','Part time'),
    ]
    SHIFT_CHOICES=[
    ('M','Morning'),
    ('E','Evening'),
    ]
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=100,default='')
    employee = models.BooleanField(default=True)
    phone_no = models.IntegerField(default=0)
    education = models.CharField(max_length=100,default='')
    adhaar_number = models.IntegerField(default=0,unique=True)
    salary_expected = models.IntegerField(default=0)
    experience = models.IntegerField(default=0)
    previous_job = models.CharField(max_length=100,default='')
    skills = models.CharField(max_length=100,default='')
    languages_known = models.CharField(max_length=100,default='')
    living_location = models.CharField(max_length=100,default='')
    working_hours = models.CharField(max_length=100, choices=WORK_CHOICES,default='')
    shift = models.CharField(max_length=100, choices=SHIFT_CHOICES,default='')
    referer_username = models.CharField(max_length=100,default='')
    points = models.IntegerField(default=0)
    recommended_user = models.BooleanField(default=False)
    def __str__(self):
            return self.user.username
    
    # def create_employee(sender, **kwargs):
    #     if kwargs['created']:
    #         employee = Employee.objects.create(user=kwargs['instance'])

    # post_save.connect(create_employee, sender= User)

class Company(models.Model):
    WORK_CHOICES=[
    ('F','Full Time'),
    ('P','Part time'),
    ]
    SHIFT_CHOICES=[
    ('M','Morning'),
    ('E','Evening'),
    ]
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    company_name = models.CharField(max_length=100,default='')
    company = models.BooleanField(default=True)
    job_type = models.CharField(max_length=100,default='')
    jobs_number = models.IntegerField(default=0)
    salary = models.IntegerField(default=0)
    minimum_qualification = models.CharField(max_length=100,default='')
    minimum_experience = models.IntegerField(default=0)
    languages_required = models.CharField(max_length=100,default='')
    job_location = models.CharField(max_length=100,default='')
    job_hours = models.CharField(max_length=100, choices=WORK_CHOICES,default='')
    job_shift = models.CharField(max_length=100, choices=SHIFT_CHOICES,default='')

    def __str__(self):
            return self.user.username


    # def create_company(sender, **kwargs):
    #     if kwargs['created']:
    #         company = Company.objects.create(user=kwargs['instance'])

    # post_save.connect(create_company, sender= User)

codefury_backend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,AuthenticationForm
from django.contrib.auth.models import User
from .models import Employee,Company

class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2',
            'email',
        )

        # help_texts = {
        #     'username': None,
        #     'password': None,
        # }

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    def save(self,commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

            return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget= forms.TextInput(attrs={'class':'my_username'}))
    password = forms.CharField(widget= forms.PasswordInput(attrs={'class':'my_password'}))

class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = (
            'phone_no',
            'referer_username',
            'education',
            'adhaar_number',
            'salary_expected',
            'experience',
            'living_location',
            'previous_job',
            'skills',
            'languages_known',
            'working_hours',
            'shift',         
        )

    def save(self,commit=True):
        profile = super(EmployeeForm,self).save(commit=False)
        profile.phone_no = self.cleaned_data['phone_no']
        profile.education = self.cleaned_data['education']
        profile.adhaar_number = self.cleaned_data['adhaar_number']
        profile.salary_expected = self.cleaned_data['salary_expected']
        profile.experience = self.cleaned_data['experience']
        profile.living_location = self.cleaned_data['living_location']
        profile.previous_job = self.cleaned_data['previous_job']
        profile.skills = self.cleaned_data['skills']
        profile.languages_known = self.cleaned_data['languages_known']
        profile.working_hours = self.cleaned_data['working_hours']        
        profile.shift = self.cleaned_data['shift']
        profile.referer_username = self.cleaned_data['referer_username']
        if profile.referer_username != "''":
            if Employee.objects.get(user=User.objects.get(username=profile.referer_username))!= None:     
                ref_profile = Employee.objects.get(user=User.objects.get(username=profile.referer_username))
                ref_profile.points = ref_profile.points + 10 
                ref_profile.save()
                if ref_profile.points >= 50:
                    ref_profile.recommended_user = True
                    ref_profile.save()
        id = User.objects.latest('date_joined')
        profile.user = id


        if commit:
            profile.save()


            return profile

class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = (
            'company_name',
            'job_type',
            'jobs_number',
            'salary',
            'minimum_qualification',
            'minimum_experience',
            'languages_required',
            'job_location',
            'job_hours',
            'job_shift'         
        )

    def save(self,commit=True):
        profile = super(CompanyForm,self).save(commit=False)
        profile.job_type = self.cleaned_data['job_type']
        profile.jobs_number = self.cleaned_data['jobs_number']
        profile.salary = self.cleaned_data['salary']
        profile.minimum_qualification = self.cleaned_data['minimum_qualification']
        profile.minimum_experience = self.cleaned_data['minimum_experience']
        profile.languages_required = self.cleaned_data['languages_required']
        profile.job_location = self.cleaned_data['job_location']      
        profile.job_hours = self.cleaned_data['job_hours']        
        profile.job_shift = self.cleaned_data['job_shift']
        profile.company_name = self.cleaned_data['comapnay_name']
        
        id = User.objects.latest('date_joined')
        profile.user = id


        if commit:
            profile.save()


            return profile

codefury_backend/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .forms import RegistrationForm,EmployeeForm,CompanyForm
from django.forms.models import inlineformset_factory
from .models import Employee,Company
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash

def home(request): 
    print(request.user)
    if request.user.is_authenticated:
        if Employee.objects.filter(user = request.user).exists():
            user = Employee.objects.get(user = request.user)
            args={'user':user,'nuser':request.user }
            print(user.points)
        else:
            args={'user':None,'nuser':request.user }
    else:
        args={'user':None ,'nuser':request.user}
    return render(request,'codefury_backend/home.html',args)

def login_redirect(request):
    if request.user:
        if Company.objects.filter(user = request.user).exists():
            return redirect(reverse('codefury_backend:candidate_search'))
        if Employee.objects.filter(user = request.user).exists():
            return redirect(reverse('codefury_backend:job_search'))

def employee_register(request):
    
    if request.method == 'POST':
        userform = RegistrationForm(request.POST)
        employeeform = EmployeeForm(request.POST)
        # reg_form = RegistrationForm(request.POST)
        if userform.is_valid() and employeeform.is_valid() :
            form1 = userform.save()
            form2 = employeeform.save()
            # if registerFormset.is_valid():
            #     registerFormset.save()
            return redirect(reverse('codefury_backend:login'))
    else:
        userform = RegistrationForm()
        employeeform = EmployeeForm()
    args = {'form1':userform, 'form2':employeeform}

    return render(request,'codefury_backend/reg_form.html',args)

def company_register(request):
    
    if request.method == 'POST':
        userform = RegistrationForm(request.POST)
        companyform = CompanyForm(request.POST)
        # reg_form = RegistrationForm(request.POST)
        if userform.is_valid() and companyform.is_valid() :
            form1 = userform.save()
            form2 = companyform.save()
            # if registerFormset.is_valid():
            #     registerFormset.save()
            return redirect(reverse('codefury_backend:login'))
    else:
        userform = RegistrationForm()
        companyform = CompanyForm()
    args = {'form1':userform, 'form2':companyform}

    return render(request,'codefury_backend/reg_form.html',args)

def job_search(request):

    # if request.method == 'GET':
    # args = {'form':JobSearchForm}
    if request.method == 'POST':
       form = request.POST
       if form:         
        
        request.session['job_type'] = form["job_type"]
        request.session['job_location'] = form["job_location"]
        return redirect(reverse('codefury_backend:jobs_list'))
    
    return render(request,'codefury_backend/job_search.html')
    
def jobs_list(request):

    
    if request.session.has_key('job_location') and  request.session.has_key('job_type'):
        job_type = request.session['job_type']
        location = request.session['job_location']
        jobs = Company.objects.filter(job_type=job_type,job_location=location)
    print(jobs)
    args={'jobs':jobs}
    return render(request,'codefury_backend/jobs_list.html',args)

def candidate_search(request):

    # if request.method == 'GET':
    # args = {'form':JobSearchForm}
    if request.method == 'POST':
       form = request.POST
       if form:         
        
        request.session['working_hours'] = form["working_hours"]
        request.session['job_location'] = form["job_location"]
        return redirect(reverse('codefury_backend:candidates_list'))
    
    return render(request,'codefury_backend/candidate_search.html')
    
def candidates_list(request):

    
    if request.session.has_key('job_location') and  request.session.has_key('working_hours'):
        
        if request.session['working_hours'] == 'Full Time':
            working_hours = 'F'
        else:
            working_hours = 'P'
        location = request.session['job_location']
        candidates = Employee.objects.filter(working_hours=working_hours,living_location=location).order_by('-points')
    args={'candidates':candidates}
    return render(request,'codefury_backend/candidates_list.html',args)

codefury_backend/templates/codefury_backend/base.html
<!DOCTYPE html>
<html >
  <head>
    {% block head %}
    {% endblock %}
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <style>

@import url("https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap");
.bse_btn{
  margin-top: 50px;
}     
#l_btn{
  float: right;
  margin-right: 50px; 
  margin-bottom: 50px;
}
#h_btn{
  float: left;
  margin-left: 50px ;    
  margin-bottom: 50px;
  display: inline-block;
  
}
.btn {
    background-color: #333; /* Green */
    border: none;
    border-radius: 10px;
    font-family: "Josefin Sans", sans-serif;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
  }
  .btn:hover {
    /* background-color: #555; */
    box-shadow: 0 2px 20px #333;
    transition: 0.4s;
  }


    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link
      href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
      rel="stylesheet"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Comfortaa:700" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
  </head>
  <body>
    {% block body %}
    {% endblock %}
    <div class="bse_btn">
    {% if user.is_authenticated %}
    <a href="{%url 'codefury_backend:logout'%}"><button type="submit" class= "btn btn-secondary" id="l_btn">Logout</button></a>
    {% endif %}    
    <a href="{%url 'codefury_backend:home'%}"><button type="submit" class= "btn btn-primary" id="h_btn">Home</button></a>
  </div>
  </body>
</html>

codefury_backend/templates/codefury_backend/candidates_list.html
{% extends 'codefury_backend/base.html' %} {% block body %}

<style>
  .iconify {
    color: lightgreen;
  }
  .container {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    background-color: whitesmoke;
    max-width: 600px;
    margin: auto;
    text-align: center;
    font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
    padding: 12px 20px;
    padding-bottom: 20px;
  }

  h1 {
    font-size: 24px;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-weight: 700;
    margin-top: 20px;
    margin-bottom: 25px;
    color: #333;
    text-transform: uppercase;
    text-align: center;
  }
  h2 {
    font-size: 22px;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-weight: 700;
    color: #333;
    text-transform: uppercase;
    text-align: center;
    padding-top: 10px ;
  }

  p {
    text-align: left;
    font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
    font-size: 20px;
    font-weight: 500;
    padding-left: 20px;
  }
  .val {
    font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
    font-size: 20px;
    font-weight: 500;
    text-align: center;
  }
  #select_btn{
    margin-bottom: 10px;
    background: #373E4A;
    color: white;
    text-align: center;
    vertical-align: middle;
    user-select: none;
    border: 1px solid transparent;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
  }
</style>
<div class="container">
  <h1 class="title">Candidates</h1>
  <br />
  {%for candidate in candidates%}

  <h2>
    Name : {{candidate.name}} {% if candidate.recommended_user %}
    <span
      class="iconify"
      data-icon="zmdi-badge-check"
      data-inline="false"
    ></span>

    {%endif%}
  </h2>

  <p>
    Experience :
    <span class="val"> {{candidate.experience}}</span>
  </p>
  <p>Qualification : <span class="val">{{candidate.education}}</span></p>
  <p>
    Salary Expected : <span class="val">{{candidate.salary_expected}}</span>
  </p>
  <p>Previous Job : <span class="val">{{candidate.previous_job}}</span></p>
  <p>Skills : <span class="val">{{candidate.skills}}</span></p>
  <p>
    Languages Known : <span class="val">{{candidate.languages_known}}</span>
  </p>
  <p>
    Living Location : <span class="val">{{candidate.living_location}}</span>
  </p>
<p>
  <a href="{%url 'codefury_backend:home'%}"><button type="submit" class= "btn btn-danger" id="select_btn">Select</button></a>
  <br />
</p>
  {% endfor %}
</div>
{% endblock %}

codefury_backend/templates/codefury_backend/jobs_list.html
{% extends 'codefury_backend/base.html' %} {% block body %}

<style>
  .container {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    background-color: whitesmoke;
    max-width: 600px;
    margin: auto;
    text-align: center;
    font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
    padding: 12px 20px;
  }

  h1 {
    font-size: 24px;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-weight: 700;
    margin-top: 20px;
    margin-bottom: 25px;
    color: #333;
    text-transform: uppercase;
    text-align: center;
  }
  h2 {
    font-size: 22px;
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-weight: 700;
    padding-left: 20px;
    color: #333;
    text-transform: uppercase;
    text-align: center;
  }

  p {
    text-align: left;
    font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
    font-size: 20px;
    font-weight: 500;
    padding-left: 20px;
  }
  .val {
    font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
    font-size: 20px;
    font-weight: 500;
    text-align: center;
  }
</style>

<div class="container">
  {%for job in jobs%}
  <h1 class="title">Company : {{job.company_name}}</h1>
  <br />
  <p>Job Description : <span class="val">{{job.job_type}}</span></p>
  <p>Salary : <span class="val">{{job.salary}}</span></p>
  <p>Job Available : <span class="val">{{job.jobs_number}}</span></p>
  <p>
    Minimum Qualification :
    <span class="val">{{job.minimum_qualification}}</span>
  </p>
  <p>
    Minimum Experience : <span class="val">{{job.minimum_experience}}</span>
  </p>
  <p>Job Location : <span class="val">{{job.job_location}}</span></p>
  <p>Job Hours : <span class="val">{{job.job_hours}}</span></p>
  <p>Shift required : <span class="val">{{job.job_shift}}</span></p>

  {% endfor %}
</div>

{% endblock %}

codefury_backend/templates/codefury_backend/login.html
<html>
<head>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>
  body {
margin: 0;
padding: 0;
font-family: 'Raleway', sans-serif;
color: #F2F2F2;
}

#container-login {
background-color: #1D1F20;
position: relative;
margin: auto;
width: 340px;
height: 445px;
border-radius: 0.35em;
box-shadow: 0 3px 10px 0 rgba(0, 0, 0, 0.2);
text-align: center;
}

#title {
position: relative;
background-color: #1A1C1D;
width: 100%;
padding: 20px 0px;
border-radius: 0.35em;
font-size: 22px;
border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.lock {
position: relative;
top: 2px;
}

.input {
margin: auto;
width: 240px;
border-radius: 4px;
background-color: #373b3d;
padding: 8px 0px;
margin-top: 15px;
}

.input-addon {
float: left;
background-color: #373b3d;
border: 1px solid #373b3d;
padding: 4px 8px;
border-right: 1px solid rgba(255, 255, 255, 0.05);
}

input[type=text] {
color: #949494;
margin: 0;
background-color: #373b3d;
border: 1px solid #373b3d;
padding: 6px 0px;
border-radius: 3px;
}

input[type=text]:focus {
border: 1px solid #373b3d;
}

input[type=password] {
color: #949494;
margin: 0;
background-color: #373b3d;
border: 1px solid #373b3d;
padding: 6px 0px;
border-radius: 3px;
}

input[type=password]:focus {
border: 1px solid #373b3d;
}

*:focus {
outline: none;
}

input[type=submit] {
margin-top: 20px;
padding: 6px 25px;
background: #373E4A;
color: #C1C3C6;
font-weight: bold;
border: 0 none;
cursor: pointer;
border-radius: 3px;
}

.register {
margin: auto;
padding: 16px 0;
text-align: center;
margin-top: 40px;
width: 85%;
border-top: 1px solid #C1C3C6;
}

#register-link {
margin-top: 10px;
padding: 6px 25px;
background: #373E4A;
color: #C1C3C6;
font-weight: bold;
border: 0 none;
cursor: pointer;
border-radius: 3px;
}
</style>
</head>
<body>
<div id="container-login" style="margin-top: 100px;">
  <div id="title">
      <i class="material-icons lock">lock</i> Login
  </div>
<div class = 'container'>
  <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Log In" />
  </form>
</div>
<div class="register">
  Don't have an account yet?
  <a href="{% url 'codefury_backend:employee_register'%}"><button id="register-link">Register here</button></a>
</div>
</div>
</body>
</html>

codefury_backend/templates/codefury_backend/navbar.html
{% extends 'codefury_backend/base.html' %} {% load static %} {%block body%}
<style>
  @import url('https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap');

  #navbar {
    background-color: #333;
    position: fixed;
    top: 0;
    width: 100%;
    display: block;
    transition: top 0.3s;
  }

  #navbar a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 15px;
    font-family: 'Montserrat', ;
    font-weight: 500;
    text-decoration: none;
    font-size: 17px;

  }

  #navbar a:hover {
    background-color: none;
    color: gray;
  }
</style>
<div id="navbar">
  <a href="{% url 'codefury_backend:home' %}">Home</a>
  {% if user.is_authenticated %}
  <a href="{% url 'codefury_backend:login' %}">Search</a>
  <a href="{% url 'codefury_backend:logout' %}">Logout</a>
  {% else %}
  <a href="{% url 'codefury_backend:login' %}">Login</a>
  <a href="{% url 'codefury_backend:register' %}">Register</a>
  {% endif %}
</div>
<script>
  // Navbar
  var prevScrollpos = window.pageYOffset;
  window.onscroll = function () {
    var currentScrollPos = window.pageYOffset;
    if (prevScrollpos > currentScrollPos) {
      document.getElementById("navbar").style.top = "0";
    } else {
      document.getElementById("navbar").style.top = "-55px";
    }
    prevScrollpos = currentScrollPos;
  };
</script>

{% endblock %}

codefury_backend/templates/codefury_backend/reg_form.html
<html>
<body>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body{
                background-color: whitesmoke;
                font-family: 'Raleway', sans-serif;
            }
            .form-control{
                    background: #373E4A;
                    color: #C1C3C6;
                    font-weight: bold;
                    border: 0 none;
                    border-radius: 3px;       
            }
             #id_username,  #id_password1, #id_password2, #id_email,#id_phone_no,#id_referer_username,#id_education,#id_adhaar_number,#id_salary_expected,#id_experience,#id_living_location,#id_previous_job,#id_skills,#id_languages_known,#id_working_hours,#id_shift, #id_company_name, #id_job_type, #id_jobs_number,
            #id_salary, #id_minimum_qualification, #id_minimum_experience, #id_languages_required, #id_job_location,
            #id_job_hours, #id_job_shift{
                background: #373E4A;
                color: #C1C3C6;
                font-weight: bold;
                border: 0 none;
                border-radius: 3px;
                display: block;
                width: 100%;
                height: calc(1.5em + .75rem + 2px);
                padding: .375rem .75rem;
                font-size: 1rem;
                line-height: 1.5;
                transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
               } 
            label{
                color: white;
            }
            input[type=text]:focus {
            border: 1px solid #373b3d;
            }
            *:focus {
            outline: none;
            }

            @media screen and (max-width: 772px) {
                #id_username, #id_password1, #id_password2, #id_email,#id_phone_no,#id_referer_username,#id_education,#id_adhaar_number,#id_salary_expected,#id_experience,#id_living_location,#id_previous_job,#id_skills,#id_languages_known,#id_working_hours,#id_shift, #id_company_name, #id_job_type, #id_jobs_number,
                #id_salary, #id_minimum_qualification, #id_minimum_experience, #id_languages_required, #id_job_location{
                 width: 98%; 
                }
            }
        </style>

  <div class="container">
    <div>
        <h2 style="text-align:center; padding-top: 10px;padding-bottom:0px;"> CREATE ACCOUNT</h2><br>
        <div class="jumbotron" style="width:40%;margin:20px auto;padding-bottom:10px;padding-top:20px;margin-bottom: 0;  background-color: #1D1F20;">
            <form method="POST">
              {% csrf_token %}
              {{ form1.as_p}}
              {{ form2.as_p}}

                
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="form-group col-md-6">

                        <button class="btn btn-lg btn-primary btn-block" style="background: #d4dceb;
                        color: rgb(37, 30, 30);
                        font-weight: bold;
                        border: 0 none;
                        cursor: pointer;
                        border-radius: 3px;">SUBMIT</button>
                    </div> 
                    <div class="col-md-3"></div>
                </div>
                
            </form>
        </div>
    </div>
</div>

</body>
</html>